language: node_js
node_js:
  - 10.16.1
cache: npm

install:
  - npm run-script install-client
  - npm i @material-ui/core
  - npm i @material-ui/icons
  - npm install mui-datatables --save

script:
  - npm run-script test
  - npm run-script build

deploy:
  provider: heroku
  api_key: $API_KEY
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master