language: node_js
node_js:
  - 10.16.1
cache: npm

script:
  - yarn test
  - yarn run build

deploy:
  provider: heroku
  api_key: $API_KEY
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
  edge: true